version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: promptuser
      POSTGRES_PASSWORD: promptpass
      POSTGRES_DB: promptdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://promptuser:promptpass@db:5432/promptdb
    ports:
      - "8001:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
volumes:
  pgdata: